services:
  chesspecker-db:
    container_name: chesspecker-db
    hostname: chesspecker-db
    image: postgres:18-alpine3.23
    ports:
      - ${DB_PORT}:5432
    volumes:
      - .pgdata:/var/lib/postgresql/data/pgdata
      - ./tools/container/postgresql-multiple-databases.sh:/docker-entrypoint-initdb.d/generate-databases.sh:ro
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${DB_PASS}
      DB_USER: ${DB_USER}
      DB_NAMES: ${DB_NAME},${DB_NAME_TEST}
      TZ: UTC
      PGTZ: UTC
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  chesspecker-node:
    container_name: chesspecker-node
    hostname: chesspecker-node
    working_dir: /usr/src/app
    image: chesspecker-node:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-attached
    env_file:
      - .env
    ports:
      - ${APP_PORT}:4200
      - ${API_PORT}:3000
      - ${API_DEBUG_PORT}:9229
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
      - web_node_modules:/usr/src/app/apps/web/node_modules
      - api_node_modules:/usr/src/app/apps/api/node_modules
    environment:
      MIKRO_ORM_CLI_CONFIG: src/shared/module/config/mikro-orm.config.ts
      PNPM_CONFIG_STORE_DIR: /usr/src/app/node_modules/.pnpm-store
      NODE_EXTRA_CA_CERTS: /usr/src/app/.cert/rootCA.pem
      PATH: $PATH:/usr/src/app/node_modules/.bin
      NG_HMR_TEMPLATES: 1
      TZ: UTC
    depends_on:
      chesspecker-db:
        condition: service_healthy
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  node_modules:
  web_node_modules:
  api_node_modules:
