name: keep-alive

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch: {}

permissions: {}

concurrency:
  group: 'keep-alive'
  cancel-in-progress: true

jobs:
  ping:
    runs-on: ubuntu-24.04
    steps:
      - name: Ping API health endpoint
        run: |
          curl --fail --silent --show-error --max-time 60 https://chess.drackp2m.dev/api
